### ISSUE TITLE
Developing on different environments has issues with baseUrl

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/PetHome#24]
We probably need to configure a .env file to store the baseUrl for our environment. 

On Visual Studio, the URL comes out differently than if we're running the command line. This forces the client app to fail, because it's hard coded to :5001 (the console app works).

We need to ensure that devops when it builds the application for deployment, that it builds with correct urls (environment)

**Comment by Junicus** [comment]
So I want to document this here, will also document it in the pr.  There are various ways to fix this, we can set a temporary environment variable when running the app.  That is nice for a temporary solution but a better solution takes a few more steps.

[Adding Custom Enviroment Variables to CRA](https://create-react-app.dev/docs/adding-custom-environment-variables)

This document describes how to add environment variables to the .env file, that file needs to be created in the root of the cra project (the js one, not the dotnet one).  It's a key/value pair, and that should be included in the git repo.  It should have variables that are generic to the app or very good defaults.

To override that you need to create a .env.*.local version.  Where * is the "environment" (development, production, etc.).  This file is the local version and it should not be included in the git repo, and there is a .gitignore in the js project to prevent that.
